# Generated by Django 3.1.5 on 2021-10-20 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_api', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deliveryaddress', models.CharField(max_length=100)),
                ('pickupaddress', models.CharField(max_length=100)),
                ('orederTime', models.TimeField(default=1634757634.3690014)),
                ('deliveryTime', models.TimeField(default=1634761234.3690014)),
                ('deliverydescription', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_api.productmodel')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
