# Generated by Django 3.1.5 on 2021-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211021_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='deliveryTime',
            field=models.TimeField(default=1634761870.1897225),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orederTime',
            field=models.TimeField(default=1634758270.1897225),
        ),
    ]
