# Generated by Django 3.1.5 on 2021-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211021_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='deliveryTime',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orederTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
